### ISSUE TITLE
mcollective::plugin isn't dependent on mcollective

### ISSUE THREAD

**Issue by matthewbarr** [voxpupuli/puppet-mcollective#108]
With this PDSL:
  class {'mcollective':  }

  mcollective::plugin { 'puppet':
    package => true,
  }

I end up getting package installation before the mcollective class runs, and installs mcollective. 

If i try to use a chain  ( -> ) / require => Class['mcollective'] I get:
Error: Could not apply complete catalog: Found 1 dependency cycle:
(Anchor[mcollective::end] => Class[Mcollective] => Mcollective::Plugin[puppet] => Package[mcollective-puppet-agent] => Class[Mcollective::Server::Service] => Service[mcollective] => Class[Mcollective::Server::Service] => Anchor[mcollective::server::end] => Class[Mcollective::Server] => Anchor[mcollective::end])

This matters because I may want to install a specific version of the mcollective packages

**Comment by jyaworski** [comment]
Hello:

Is this still an issue?

**Comment by jyaworski** [comment]
Does #285 address this?
