### ISSUE TITLE
Missing tests for SSL parameters

### ISSUE THREAD

**Issue by ffrank** [voxpupuli/puppet-mcollective#251]
It was [discovered](https://github.com/puppet-community/puppet-mcollective/pull/244#commitcomment-13939566) by @kmcfate that a breaking [change](https://github.com/puppet-community/puppet-mcollective/pull/244) to some parameter implementations raised no red flags.

Needs coverage.

**Comment by jyaworski** [comment]
What's the status of this?

**Comment by ffrank** [comment]
I should really sit down and write those tests.

**Comment by ffrank** [comment]
Just wracked my brain over this for a while. I think this is a non-issue after all. Here's what happened:

The contributor missed the fact that the `ssl_server_private` and `ssl_server_public` parameters were indeed used in a `file/source` parameter. They used them in a different way to specify a file location on the target system. This clashes with existing manifests of course.

The problem with coverage is: It really doesn't seem to make much sense to add a test case that supplies a value to these optional parameters, and then makes sure some completely unrelated `setting` resources take a sensible value.

A comprehensive acceptance test suite *might* catch this, but that's a tall order I feel. Bottom line is, unit tests would not have saved us, this should not have passed (my) review.

Closing this topic.
