### ISSUE TITLE
Missing facts

### ISSUE THREAD

**Issue by raphink** [voxpupuli/puppet-mcollective#262]
When using facter 3, the module uses `facter --yaml` in the crontab, which results in missing facts in the YAML file (such as `puppetversion` for example).

`puppet facts --render-as yaml` outputs all the facts previously returned by facter, but the format is slightly different (it uses a `values` hash). The solution might be to adapt `refresh-mcollective-metadata.rb` to facter 3 to call the Puppet `facts` face and return the `values` hash as YAML.

**Comment by jyaworski** [comment]
Hello:

Is this still an issue?

**Comment by jhg03a** [comment]
Yes.  I've run across this while trying to track down not finding the correct puppet environment fact during an mco facts query.

```
jhg03a@VMLifeboat01:~$ wc -l /etc/puppetlabs/mcollective/facts.yaml 
125 /etc/puppetlabs/mcollective/facts.yaml

jhg03a@VMLifeboat01:~$ facter -p | wc -l
2016-02-02 18:02:11.255835 WARN  puppetlabs.facter - skipping external facts for "/home/jhg03a/.puppetlabs/opt/puppet/cache/facts.d": No such file or directory
347

jhg03a@VMLifeboat01:~$ sudo facter -p | wc -l
1299

jhg03a@VMLifeboat01:~$ puppet facts | wc -l
444

jhg03a@VMLifeboat01:~$ sudo puppet facts | wc -l
1521

jhg03a@VMLifeboat01:~$ puppet --version
4.3.0
jhg03a@VMLifeboat01:~$ facter -v
3.1.2 (commit 8d2c0797d95ad74a1c9b5ec5a3a92c694df2dd0b)

jhg03a@VMLifeboat01:~$ env | grep FACTER*

# Puppet Name: refresh-mcollective-metadata
PATH=/opt/puppet/bin:/opt/puppetlabs/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
0,15,30,45 * * * * facter --yaml >/etc/puppetlabs/mcollective/facts.yaml 2>&1
```

I don't use external facts, but I do use custom facts distributed through puppet.  I'm also using the default root crontab entry.

**Comment by jhg03a** [comment]
Looking at the cron job, the facter command is missing the -p argument that would pull in puppet facts.

**Comment by bastelfreak** [comment]
@jhg03a I merged the fix and this should be done. can you verify this and close the PR?

**Comment by jhg03a** [comment]
Yep.  It appears to fix things.

**Comment by jhg03a** [comment]
This can be closed

**Comment by akomakom** [comment]
I found the change, it's from June, so after this issue was closed.  
https://github.com/voxpupuli/puppet-mcollective/commit/a47f45593926e616727194d08a0bfa87db306557
