### ISSUE TITLE
Upload current version to puppet forge

### ISSUE THREAD

**Issue by jlyheden** [voxpupuli/puppet-mcollective#264]

**Comment by igalic** [comment]
I  think a resync from modulesync_config would be a good first step. but would to mind submitting a pr with a Changelog update?

**Comment by jyaworski** [comment]
What's the status of this?

**Comment by jyaworski** [comment]
@neoice wants this as well.

**Comment by neoice** [comment]
here's the exact post: https://github.com/voxpupuli/puppet-mcollective/pull/276#issuecomment-189684973

sorry, didn't think to search for an open issue :smile:

**Comment by hdeadman** [comment]
This can be closed: Version 2.2.0 released May 21st 2016
