### ISSUE TITLE
Broken for ruby 1.8.7

### ISSUE THREAD

**Issue by matonb** [voxpupuli/puppet-mcollective#297]
This change breaks compatibility with ruby 1.8.7

https://github.com/voxpupuli/puppet-mcollective/blob/master/lib/puppet/parser/functions/mco_array_to_string.rb#L3

The older syntax
`Puppet::Parser::Functions.newfunction(:mco_array_to_string, :type -> :rvalue) do |args|`

Still works with ruby 2.2.4, only rubocop is complaining.

Puppet 4 ships wit ruby 2.1.8 is testing against 2.2.4 required at the moment ?

**Comment by bastelfreak** [comment]
Hi,
we dropped ruby1.8.7 support a while back. Currently we test against 1.9-2.3. Please use one of the older releases if you still need 1.8.7 support or upgrade your Ruby Version.

**Comment by matonb** [comment]
So you're not supporting Enterprise Linux 6 ?

**Comment by alexjfisher** [comment]
So you don't support RHEL6 anymore even though it's in the metadata.json?

Puppet 4 on EL6 comes with a later ruby, but this module [isn't puppet 4 compatible](https://github.com/voxpupuli/puppet-mcollective/issues/278).

Would reverting to the old hash style for that function and adding a rubocop control comment not be ok?

**Comment by bastelfreak** [comment]
After checking the code: the last release should still support ruby1.8.7, just our master branch doesn't. We've got several open issues here and we are trying to resolve them, this includes adding Puppet4 support.

---

We're aware of the fact that RHEL still has support from RedHat. But that system is sooo old, most of the stuff there as no upstream support anymore, for example their shipped Ruby version. Testing and developing against that old thing is really painful for us. Many of our development tools don't support 1.8.7 anymore. Also there aren't any security patches from the Ruby developers anymore. We decided to drop 1.8.7 support for all modules in the voxpupuli namespace. Mostly everything except for RHEL ships a newer ruby version and in 99% of the cases you can use the new Puppet AIO packages which ship their own embedded Ruby or you can build them by yourself.
