### ISSUE TITLE
Deprecate and archive puppet-mcollective

### ISSUE THREAD

**Issue by smortex** [voxpupuli/puppet-mcollective#396]
* This module does not support Puppet 6+ (#395);
* Puppet 7+ does not ship with MCollective anymore;
* [Choria](https://choria.io/) has supeseded MCollective and is fully supported on Puppet 7 with the modules form the [choria organization](https://forge.puppet.com/modules/choria).

For these reasons, this module does not make sense in a modern Puppet ecosystem, therefore I propose to deprecate and archive it.

**Comment by tuxmea** [comment]
+1 @bastelfreak

**Comment by TheMeier** [comment]
reminder: please archive :D
